# Test to split mpcorb.sof file in chunks to speed up calculations

In [1]:
import tychoCatServer.helper as hlp
import pandas as pd

In [2]:
dic=hlp.read_sof_file('mpcorb.sof')

In [3]:
df=pd.DataFrame(dic).transpose()

In [4]:
df

,Tp,Te,q,i,Om,om,e,rms,n_o,Tfirst,Tlast,Perts,Perts_ext,H,G
1,20270713.533732,20250505,2.546423,10.5878,80.25221,73.27343,0.079401,0.8,7330,18001226,20241101,M-v,30k,3.34,0.15
2,20230307.358019,20250505,2.131552,34.92402,172.8953,310.91037,0.23054,0.75,8964,18031121,20240927,M-c,28k,4.11,0.15
3,20230402.336672,20250505,1.987119,12.98651,169.82994,247.85972,0.255947,0.83,7523,18030801,20240607,M-v,3Ek,5.18,0.15
4,20250814.428569,20250505,2.148619,7.14394,103.70297,151.58335,0.090107,0.82,7647,18200425,20240306,M-p,18k,3.25,0.15
5,20240508.04674,20250505,2.093772,5.35887,141.45353,359.31775,0.187441,0.86,3184,18440329,20250213,M-v,3Ek,6.99,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P/2025 C1,20250208.49084,20250209,2.74688,7.52434,9.11673,187.27791,0.343802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C/2025 D1,20280518.31942,20231227,14.122774,84.50734,312.87576,185.84287,1.002825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/2025 D2,20280115.43327,20250216,7.226447,5.25648,255.20018,303.78899,0.245797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/2025 D3,20240726.00147,20250215,2.966608,9.64688,186.62995,294.55712,0.251744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P/2025 D4,20250214.31782,20241008,3.254896,15.94137,233.11888,332.89699,0.633978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN